{% set name = "black" %}
{% set version = "21.5b2" %}

package:
  name: {{ name|lower }}-recipe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fc0e0a2c8ae7d269dfcf0c60a89afa299664f3e811395d40b1922dff8f854b5

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build_base.sh
    build:
      noarch: python
      entry_points:
        - black = black:patched_main
        - black-primer = black_primer.cli:main
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools_scm
      run:
        - python >=3.6
        - appdirs
        - click >=7.1.2
        - dataclasses >=0.6
        - mypy_extensions >=0.4.3
        - pathspec >=0.8.1,<1
        - regex >=2020.1.8
        - toml >=0.10.1
        - typed-ast >=1.4.2
        - typing_extensions >=3.7.4
    test:
      requires:
        - pip
      commands:
        - black --help
        - black-primer --help
        - pip check

  - name: {{ name }}d
    build:
      noarch: python
      entry_points:
        - blackd = blackd:patched_main
    requirements:
      run:
        - {{ pin_subpackage('black', exact=True) }}
        - aiohttp >=3.6.0
        - aiohttp-cors >=0.4.0
    test:
      commands:
        - black --help
        - black-primer --help
        - blackd --help
  
  - name: {{ name }}-colorama
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('black', exact=True) }}
        - colorama  >=0.4.3
    test:
      commands:
        - black --help
        - black-primer --help

about:
  home: https://github.com/python/black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'The Uncompromising Code Formatter'

  description: |
    Black is the uncompromising Python code formatter. By using it, you agree
    to cease control over minutiae of hand-formatting. In return, Black gives
    you speed, determinism, and freedom from pycodestyle nagging about
    formatting. You will save time and mental energy for more important matters.
  doc_url: https://github.com/psf/black
  dev_url: https://github.com/psf/black

extra:
  recipe-maintainers:
    - carlodri
    - ambv
    - mariusvniekerk
    - xhochy
